ALTER TYPE "PaymentServiceKey" ADD VALUE IF NOT EXISTS 'IDENTITY_REVEAL_WITH_CARD';
ALTER TYPE "PaymentServiceKey" ADD VALUE IF NOT EXISTS 'IDENTITY_REVEAL_WITH_PAGE';
ALTER TYPE "PaymentServiceKey" ADD VALUE IF NOT EXISTS 'IDENTITY_REVEAL_WITH_CARD_AND_PAGE';
